# TODO move env to container spec
# TODO add prometheus annotations

# Workflow Engine is deployed as just another Fission environment.
apiVersion: fission.io/v1
kind: Environment
metadata:
  name: workflow
  namespace: default
spec:
  version: 2
  runtime:
    image: "{{ .Values.envImage }}:{{.Values.tag}}"
    env:
    - name: ES_NATS_URL
      value: "nats://{{ .Values.nats.authToken }}@{{ .Values.nats.location }}.{{ .Values.fnenv.fission.ns }}:{{ .Values.nats.port }}"
    - name: ES_NATS_CLUSTER
      value: "{{ .Values.nats.cluster }}"
    - name: FNENV_FISSION_CONTROLLER
      value: "{{ .Values.fnenv.fission.controller }}.{{ .Values.fnenv.fission.ns }}"
    - name: FNENV_FISSION_EXECUTOR
      value: "{{ .Values.fnenv.fission.executor }}.{{ .Values.fnenv.fission.ns }}"
  builder:
    image: "{{ .Values.buildEnvImage }}:{{.Values.tag}}"
    command: "defaultBuild"
  allowedFunctionsPerContainer: infinite

# Workflow Apiserver is an optional component that allows users to query the workflows API through the Fission apiserver.
{{ if .Values.apiserver }}
apiVersion: app/v1
kind: Deployment
metadata:
  name: workflows-apiserver
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        svc: workflows-apiserver
    spec:
      containers:
      - name: workflows-apiserver
        image: "{{ .Values.bundleImage }}:{{.Values.tag}}"
        imagePullPolicy: {{ .Values.pullPolicy }}
        command: ["/fission-workflows-bundle"]
        args: [
        # Only run components related to accessing the API
          "--nats",
          "--api-http",
          "--api-workflow-invocation",
          "--api-workflow",
          "--api-admin",
          "--metrics",
        ]
        env:
        - name: ES_NATS_URL
          value: "nats://{{ .Values.nats.authToken }}@{{ .Values.nats.location }}.{{ .Values.fnenv.fission.ns }}:{{ .Values.nats.port }}"
        - name: ES_NATS_CLUSTER
          value: "{{ .Values.nats.cluster }}"
        - name: FNENV_FISSION_EXECUTOR
          value: "{{ .Values.fnenv.fission.executor }}.{{ .Values.fnenv.fission.ns }}"
        - name: FNENV_FISSION_CONTROLLER
          value: "{{ .Values.fnenv.fission.controller }}.{{ .Values.fnenv.fission.ns }}"
---
{{ end }}